FROM postgres:latest
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB dvdrental
# docker exec -i postgres pg_restore -U postgres -F t -d dvdrental < ~/Downloads/dvdrental.tar
# docker exec -it dvdrental psql -U postgres -d dvdrental
