FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD mysql
ENV MYSQL_PASSWORD mysql
ENV MYSQL_USER mysql
ENV MYSQL_DATABASE ORG
# docker run --network mysql_net --name mysql -v employees:/var/lib/mysql -d mysql:tag
# connect to other sql
# docker run --network mysql_net -it --rm mysql mysql -h mysql -u mysql -p
